.gitignore, bower.json, index.html, manifest.json, polymer.json, style.css
Adding the mission to the site as we don't really have any other content for it right now.
=> Add the mission to the site

_includes/footer.liquid
@ElenaFdR what do you think of this?
=> Update contact info

careers/index.md
Spotted as part of prep for new Foundation 1 pager.
-----
[View rendered careers/index.md](https://github.com/publiccodenet/http/blob/Prep-for-new-Foundation-1-pager/careers/index.md)
=> Careers page: smoother CTA, small style tweaks

team/felix-faassen.md
Added Felix profile to team page. Please check spelling correct format ;-)
-----
[View rendered team/felix-faassen.md](https://github.com/publiccodenet/publiccode.net/blob/felixfaassen-added-felix-to-team-page/team/felix-faassen.md)
=> added felix to team page

README.md
Simple addition.
-----
[View rendered README.md](https://github.com/publiccodenet/publiccode.net/blob/clarify-repo-description/README.md)
=> Clarify description of repository

team/deborah-meibergen.md
made a small update to my bio whilst testing Atom - so far, so good :)
-----
[View rendered team/deborah-meibergen.md](https://github.com/publiccodenet/publiccode.net/blob/updating-bio/team/deborah-meibergen.md)
=> updated bio

codebase-stewardship/index.html, codebases/openzaak.md
-----
[View rendered codebases/openzaak.md](https://github.com/publiccodenet/publiccode.net/blob/develop/codebases/openzaak.md)
=> Release 20200928

who-we-are/index.md
Add team/ to the URI in img tag src property in who-we-are/index.md.
-----
[View rendered who-we-are/index.md](https://github.com/jlowry/publiccode.net/blob/Who-we-are/who-we-are/index.md)
=> Fixed team photograghs

index.html
This follows a discussion in the board meeting where we discussed whether this sentence shouldn't reflect more closely what we do now instead of a more open statement. I hope this wording helps us achieve our immediate priorities more and I think it would be a worthwhile improvement.
I've taken the wording from [our translation of the articles of association](https://about.publiccode.net/organization/articles-of-association.html).
=> Use articles of association goal as introduction

_config.yml
To enable compiling of .scss files (added in #110).
=> Add coffeescript plugin

team/alba-roza.md, team/boris-van-hoytema.md, team/claus-mullie.md, team/deborah-meibergen.md, team/elena-findley-de-regt.md, team/eric-herman.md, team/felix-faassen.md, team/jan-ainali.md, team/laura-scheske.md
This is a short term fix so that we can release again. 
This is a workaround for the problem identified in [About repo #825](https://github.com/publiccodenet/about/issues/825).
-----
[View rendered team/alba-roza.md](https://github.com/publiccodenet/publiccode.net/blob/remove-twitter-links/team/alba-roza.md)
[View rendered team/boris-van-hoytema.md](https://github.com/publiccodenet/publiccode.net/blob/remove-twitter-links/team/boris-van-hoytema.md)
[View rendered team/claus-mullie.md](https://github.com/publiccodenet/publiccode.net/blob/remove-twitter-links/team/claus-mullie.md)
[View rendered team/deborah-meibergen.md](https://github.com/publiccodenet/publiccode.net/blob/remove-twitter-links/team/deborah-meibergen.md)
[View rendered …
=> Remove links Twitter from team bios

codebases/index.html, codebases/signalen.html
=> Change status on Signalen to incubation

careers/index.md
This is a change for the sake of troubleshooting the develop/master mystery commits issue.
-----
[View rendered careers/index.md](https://github.com/publiccodenet/publiccode.net/blob/careers-index-human-readable/careers/index.md)
=> editing careers index FTW!

careers/index.md, codebases/signalen.html
-----
[View rendered careers/index.md](https://github.com/publiccodenet/publiccode.net/blob/release-202010211-4/careers/index.md)
=> Release 202010211 4

.github/workflows/link-check.yml, .github/workflows/test.yml, .travis.yml, Gemfile, script/check-new-links.sh, script/cibuild.sh, script/test-with-link-check.sh, script/test-without-link-check.sh, who-we-are/team/ben-cerveny.md
-----
[View rendered who-we-are/team/ben-cerveny.md](https://github.com/publiccodenet/publiccode.net/blob/gh-actions-20210309/who-we-are/team/ben-cerveny.md)
=> Gh actions 20210309

careers/content-editor.md
Draft PR pending board aproval for this vacancy.
I've refocused this to highlight our upcoming awareness raising push - I'd welcome feedback on whether this is now too broad a role with unclear seniority/experience required.
-----
[View rendered careers/content-editor.md](https://github.com/publiccodenet/publiccode.net/blob/content-editor/careers/content-editor.md)
=> Add communications editor job description

careers/content-editor.md
-----
[View rendered careers/content-editor.md](https://github.com/publiccodenet/publiccode.net/blob/content-editor-2/careers/content-editor.md)
=> Communications editor role, improved with @neb's feedback

index.html
Quick reading guide to get to know us in case someone doesn't have enough time to go all over our documentation.
The uploaded leaflet is in PDF format.
=> Add leaflet of case for support

codebases/signalen.html
=> Update Signalen replicators

careers/administrative-employee.md
Based on the template.
Co-authored-by: Eric Herman <eric@publiccode.net>
-----
[View rendered careers/administrative-employee.md](https://github.com/publiccodenet/publiccode.net/blob/administrative-employee-position/careers/administrative-employee.md)
=> Administrative employee position

careers/administrative-employee.md
As suggested by @ericherman
-----
[View rendered careers/administrative-employee.md](https://github.com/publiccodenet/publiccode.net/blob/oxford-comma-administrative-employee/careers/administrative-employee.md)
=> Add oxford comma

careers/administrative-employee.md
Including a mention of holiday pay and paid vacation.
Change to allow for some space in development of the salary framework.
-----
[View rendered careers/administrative-employee.md](https://github.com/publiccodenet/publiccode.net/blob/change-pay-administrative-employee/careers/administrative-employee.md)
=> Change salary for administrative employee

index.html
Fixes #215
(We don't seem to link this file from any of our other repositories.)
=> Fix link to case for support pdf and remove early version

codebase-stewardship/index.html
=> Hot fix - Replace markdown with html formatting

codebases/openzaak.html
=> Add videos to OpenZaak page

codebase-stewardship/index.html
Co-authored-by: Jan Ainali <ainali.jan@gmail.com>
=> Add section about incubation

who-we-are/index.md
null
-----
[View rendered who-we-are/index.md](https://github.com/publiccodenet/publiccode.net/blob/DPGA-membership/who-we-are/index.md)
=> Add DPGA membership

standard-for-public-code/index.md
Fixes #214
-----
[View rendered standard-for-public-code/index.md](https://github.com/publiccodenet/publiccode.net/blob/collaborative-standard/standard-for-public-code/index.md)
=> Focus standard on collaboration

standard-for-public-code/index.md, who-we-are/index.md
Tiny release, but will also trigger a rebuild with the updates in the Jekyll theme.
-----
[View rendered standard-for-public-code/index.md](https://github.com/publiccodenet/publiccode.net/blob/release-20221110/standard-for-public-code/index.md)
=> Release 20221110

live.html
For now, with the link to our last stream.
=> Add livestream page

who-we-are/former-team-members.md
=> no fully qualified URLs in redirects

codebases/omgevingsbeleid.html, codebases/openzaak.html, codebases/signalen.html, who-we-are/former-team-members.md
=> Release 20230710

codebases/omgevingsbeleid.html
=> Fix grammar error

who-we-are/index.md
The new website design spreads this content over 3 pages, so this is a short update to reflect our current reality.
=> New 'Who we are' that introduces North America

codebases/openzaak.html
=> Update OpenZaak assessment link

careers/intern.md
keep the page, as we may wish to restore the previous version from git
=> remove internship position

careers/intern.md
=> Release 20231107 2

.github/workflows/link-check.yml, .github/workflows/test.yml
https://github.com/actions/checkout/blob/main/CHANGELOG.md
=> Update github actions/checkout from v2 to v4
