publiccodenet/publiccode.net

- codebase-stewardship/index.html
These are minimal changes to:
- remove the banner warning that we're not yet doing stewardship
- update out of date language so it matches our statements in other places
It doesn't change:
- the salesy tone
- the substantive description of what we offer in stewardship
- the images
> MVP updated stewardship text (bugfix)

- _config.yml
- membership/founding-membership.md
- membership/index.md
Dividing members into founding members and members is no longer part of our membership model.
-----
[View rendered membership/founding-membership.md](https://github.com/publiccodenet/publiccode.net/blob/founding-members/membership/founding-membership.md)
> Remove references to founding members

- codebases/openzaak.md
The old URL to the draft website is now broken.
-----
[View rendered codebases/openzaak.md](https://github.com/publiccodenet/publiccode.net/blob/openzaaklink/codebases/openzaak.md)
> Update OpenZaak product website URL

- codebase-stewardship/index.html
Fixes #92.
There are no other problematic references to services on publiccode.net.
> Remove reference to us providing services from /codebase-stewardship

- _config.yml
The layout wasn't selected for the bio pages since the path for assigning that layout was not changed.
Jekyll documentation on Front Matter defaults: https://jekyllrb.com/docs/configuration/front-matter-defaults/
> Fix path in default variables

- _config.yml
We don't need this after all.
Reverts publiccodenet/publiccode.net#115
> Revert "Add coffeescript plugin"

- script/test.sh
This should unblock the Travis error on #111 (tripped by the lightbox on the codebase pages).
> HTMLproofer ignore #

- .well-known/matrix/client
- .well-known/matrix/server
We've tried using Riot for team and community communications
and have decided against using it.
Thus we don't need these identifiers anymore.
> Remove Matrix configuration

- _layouts/marketing-page.html
- index.html
To enlarge the "Join us" link on the index page, I'm removing some complex CSS apparently intended to universally reduce the text size of secondary paragraphs, and putting in place an explicit "subtext" class to make this smaller text size manual.
Addresses https://github.com/publiccodenet/publiccode.net/issues/136
> Adding explicit class in place of complex/unused font-size switches

- index.html
Removing periods from within hyperlinked call to action sentences should make this page slightly less visually cluttered.
> Standardize periods after hyperlinked sentences on index

- script/test.sh
This should narrow the matching to ignore only the lightbox links but still include links with a "#_" somewhere within, for example a link like: "example.org/docs.html#_private_method_foo"
> Narrow link check 20210201

- .travis.yml
Addressing Travis failure:
zeitwerk-2.4.2 requires ruby version >= 2.4.4,
which is incompatible with the current version, ruby 2.4.0p0
https://travis-ci.com/github/publiccodenet/publiccode.net/builds/217479220
> Ruby version 2.4.0 -> 2.4.7 for Travis

- careers/communications-editor.md
This should help with SEO and remove any possibility for confusion re the job title.
-----
[View rendered careers/communications-editor.md](https://github.com/publiccodenet/publiccode.net/blob/fix-URL-on-communications-editor-job/careers/communications-editor.md)
> Fix URL to match job title for communications editor job

- codebases/signalen.html
Previous link seems to no longer exist. New link is to that video on Signalen's account.
> Updating the Signalen explainer video link

- .github/workflows/link-check.yml
Fix the crontab to run at a particular minute, rather than
imply every minute for an hour.
> Specify minute on link-check.yml cron table entry

- who-we-are/former-team-members.md
- who-we-are/index.md
Fixes #239
-----
[View rendered who-we-are/former-team-members.md](https://github.com/publiccodenet/publiccode.net/blob/former-team-members/who-we-are/former-team-members.md)
[View rendered who-we-are/index.md](https://github.com/publiccodenet/publiccode.net/blob/former-team-members/who-we-are/index.md)
> Add page and redirects for former team members

- Gemfile
fix "htmlproofer 4.0.1 | Error:  invalid option: --typhoeus-config"
> Pin html-proofer ~> 3.19

- OSPO.md
OSPO.md was put into caps because that's grammatically correct for an abbreviation. However, most people won't expect only part of a URL to be in caps. 
Currently typing the URL with the wrong capitalization results in a 404. This PR aims to help people get to the right place.
> Add redirects with other capitalization to OSPO.md

- standard-for-public-code/index.md
I thought the "cannot" gave the wrong impression, so I expanded the section.
> Clarify how to certify existing codebases

- careers/intern.md
This prevents the intern position from showing up in the careers index under the "Open positions" heading.
> change type of intern position to "Closed"

- standard-for-public-code/index.md
> Tweaks introduction to standard

- standard-for-public-code/certification.md
- standard-for-public-code/index.md
Starting the work towards #322 by just removing the bulk of the certification text to a separate page.
The text on the original page can be seen just as a temporary placeholder until we have made a full review of the standard page.
> Break out certification to separate page

- script/test-with-link-check.sh
In https://github.com/publiccodenet/publiccode.net/actions/runs/8476081170/job/23225131711 it can be seen:
```
- ./_site/who-we-are/former-team-members.html
*  External link https://www.linkedin.com/in/albaroza/ failed: 999 No error
```
Note: 999 is _very_ wrong by linkedin, not a valid HTTP status code
> test-with-link-check: ignore linkedin
